hub:
  cookieSecret: longhashthatissecret
  imagePullPolicy: Always
ingress:
  enabled: true
  hosts:
    - some.public.url
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
  tls:
   - hosts:
      - some.public.url
     secretName: kubelego-tls-jupyterhub
proxy:
  secretToken: anotherlonghashthatissecret
  https:
    hosts:
      - some.public.url  # Probably should work out how to ensure this works, or remove it..
    letsencrypt:
      contactEmail: legit@email.com
singleuser:
  cloudMetadata:
    enabled: true
  image:
    name: opendatacube/jupyterhub
    tag: 1.5.4
  extraEnv:
    DATACUBE_CONFIG_PATH: /conf/datacube.conf  # This has write access.
    DB_DATABASE: opendatacube
    DB_HOSTNAME: db
    DB_USERNAME: postgres
    DB_PASSWORD: secretpassword
    DB_PORT: 5432
  extraContainers:
    - name: db
      image: postgres
      env:
      - name: POSTGRES_USER
        value: 'posgres'
auth:
  type: github
  github:
    clientId: "secretid"
    clientSecret: "longsecret"
    callbackUrl: "http://some.public.url/hub/oauth_callback"
